// Generated by CoffeeScript 1.4.0
var Car, Engine, chevy, ford,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Engine = (function() {

  function Engine(running) {
    this.running = running;
  }

  Engine.prototype.start = function() {
    return this.running = true;
  };

  return Engine;

})();

Car = (function(_super) {

  __extends(Car, _super);

  function Car() {
    return Car.__super__.constructor.apply(this, arguments);
  }

  Car.prototype.turnKey = function() {
    if (this.running) {
      return "Car is already running";
    } else {
      this.start();
      return "Car is now started";
    }
  };

  return Car;

})(Engine);

ford = new Car(true);

chevy = new Car(false);

console.log(ford.turnKey());

console.log(chevy.turnKey());
